### ISSUE TITLE
track_features array somehow overwrites build_flavor

### ISSUE THREAD

**Issue by wolfv** [openSUSE/libsolv#377] opened 2020-04-24 05:12 UTC
I'm not really sure how this happens, any ideas?

**Comment by wolfv** [comment] 2020-04-24 05:20
The BUILD_FLAVOR and TRACK_FEATURES ids seem to be distinct. However, my build_flavor for a single solvable now reads like this:

`gpu_0, gpu, eigen, mkl, gpu, mkl, eigen, gpu, eigen, mkl, gpu, mkl, eigen, gpu, eigen, mkl, py27_0` (which are 2 build flavors and a bunch of trackfeatures mixed up).

**Comment by wolfv** [comment] 2020-04-24 09:15
@mlschroe any idea? I am happy to push a PR but unsure how this happens exactly.

**Comment by mlschroe** [comment] 2020-04-24 09:20
Can you point me to a repo where this happens?

**Comment by wolfv** [comment] 2020-04-24 09:31
let me see.

If one uses the latest version of mamba, and tries to install `pytorch`, it thinks the build string for cudatoolkit is empty, but the build string for the `_pytorch_select` meta package is `gpu_0, gpu, eigen, mkl, gpu, mkl, eigen, gpu, eigen, mkl, gpu, mkl, eigen, gpu, eigen, mkl, py27_0` (where `gpu_0` and `py27_0` look like build strings but the other might be track features (at least build strings shouldn't have spaces or commas in them).

pytorch is taken from this repo: https://repo.anaconda.com/pkgs/main/linux-64/repodata.json

let me see if one repo is enough to run into this.

**Comment by mlschroe** [comment] 2020-04-24 09:41
Ok, I can reproduce this. It's caused by the packages/packages.conda commit.

**Comment by wolfv** [comment] 2020-04-24 09:42
Awesome.

**Comment by mlschroe** [comment] 2020-04-24 09:55
Fixed now. Do you need another release?

**Comment by wolfv** [comment] 2020-04-24 09:58
if possible that would be :rocket:

**Comment by wolfv** [comment] 2020-04-24 09:59
and thanks a lot! (we can also patch the current release and increase the build number, but a new release would definitely be nicer).

**Comment by mlschroe** [comment] 2020-04-24 10:03
0.7.13 released. Just for you ;-)

**Closed by mlschroe** 2020-04-24 10:03 UTC

**Comment by wolfv** [comment] 2020-04-24 10:04
thanks a lot :bow:
