### ISSUE TITLE
crash with data_skip on Fedora 21+22 using dnf

### ISSUE THREAD

**Issue by tuxmaster** [openSUSE/libsolv#86] opened 2015-05-30 07:06 UTC
Hello can the developer take an look on it?
Her the original reports with debug information:
https://bugzilla.redhat.com/show_bug.cgi?id=1225975
https://bugzilla.redhat.com/show_bug.cgi?id=1175906

**Comment by mlschroe** [comment] 2015-06-01 09:22
I already saw those bugs, but to me it looks like somebody is messing with the memory. This can be a libsolv bug, it it also may be in librepo, libcomps or hawkey.

**Comment by tuxmaster** [comment] 2015-06-01 10:28
How can we do more debugging?

**Comment by mlschroe** [comment] 2015-06-01 10:29
Can you easily reproduce the crash?

**Comment by tuxmaster** [comment] 2015-06-01 10:45
Yes, I have create an repo which only contains one package.
The package only contains the gpg key  for the signet rpm's and the repo description file.
I can send you the url for it.

**Comment by mlschroe** [comment] 2015-06-01 11:48
Sure, please send the url.

**Comment by tuxmaster** [comment] 2015-06-01 13:09
1. step add the CA root certificate to Fedora
cd /etc/pki/ca-trust/source/anchors/
wget -c http://www.cacert.org/certs/root.crt -O cacert.pem
update-ca-trust
2. call yum (yum-deprecated) install https://katlin.terrortux.de/Software/22/x86_64/KatLin-3.0.0-1.fc22.noarch.rpm
3. call dnf update ->crash
4. call yum update ->work

**Comment by mlschroe** [comment] 2015-06-01 16:58
Thanks, I could reproduce the crash. It really is a bug in libsolv. Oh my.

It turned out that the sha512 checksums in the repomd.xml file led to the crash. The support for sha512 was missing in data skip... Sorry.
Fixed with commit #3f1627007cecdbe4b8f8f41ab560cac02266fb37

**Closed by mlschroe** 2015-06-01 16:58 UTC

**Comment by tuxmaster** [comment] 2015-06-01 17:03
Thanks for the fast fix.
