### ISSUE TITLE
obsoletes with different versions are confusing solver

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#191] opened 2017-04-06 16:53 UTC
```
repo system 0 testtags <inline>
#>=Pkg: a52dec 1 1 x86_64
#>=Prv: liba52.so.0()
#>=Pkg: foo 1 1 x86_64
#>=Req: liba52.so.0()
repo available 0 testtags <inline>
#>=Pkg: a52dec 1 4 x86_64
#>=Obs: a52dec < 1-2
#>=Pkg: a52dec-libs 1 4 x86_64
#>=Prv: liba52.so.0()
#>=Obs: a52dec < 1-3
system x86_64 rpm system
poolflags implicitobsoleteusescolors
solverflags allowvendorchange keepexplicitobsoletes bestobeypolicy keeporphans yumobsoletes
job update all packages [forcebest]
result transaction,problems <inline>
#>erase a52dec-1-1.x86_64@system a52dec-libs-1-4.x86_64@available
#>install a52dec-libs-1-4.x86_64@available
```

If I change `1-2` to `1-3`, it will do:
```diff
-erase a52dec-1-1.x86_64@system a52dec-libs-1-4.x86_64@available
+upgrade a52dec-1-1.x86_64@system a52dec-1-4.x86_64@available
```

This makes DNF to report packages with broken dependencies while it is not (probably some bug in libdnf, but message is wrong in libsolv as well).

**Comment by ignatenkobrain** [comment] 2017-04-07 04:03
actually, it is not only wrong message, but it is wrong behavior -- if you have 2 obsoletes where one is obsoleting older version (you still match it), it will be replaced by one package instead of installing 2

**Comment by mlschroe** [comment] 2017-04-07 16:09
This is more or less a duplicate of #146. I.e. it works like designed, the special "yum magic obsoletes handling" is only triggered when the obsoletes are identical.

**Closed by mlschroe** 2017-04-07 16:09 UTC
