### ISSUE TITLE
Installing by provides doesn't pick best package

### ISSUE THREAD

**Issue by jlebon** [openSUSE/libsolv#165] opened 2016-12-02 20:52 UTC
```
repo system 0 empty
repo test 0 testtags <inline>
#>=Pkg: foo 2 1 noarch
#>=Pkg: bar 2 1 noarch
#>=Prv: foo = 1

system x86_64 rpm system

job install provides foo
result transaction,problems <inline>
#>install foo-2-1.noarch@test
```

```
Results differ:
+install bar-2-1.noarch@test
-install foo-2-1.noarch@test
```

Interestingly, we could work around this by explicitly adding `#>=Prv: foo = 2` to pkg `foo` (which I would think was already implied). But even then, the problem appears again if we want to install the provides for both `foo` *and* `bar`.

**Comment by mlschroe** [comment] 2016-12-08 13:54
Hmm, when I implemented the provides comparison feature, I wrote code that it doesn't check provides with different layout, e.g. "1" and "2-1" in your case.

I can't remember the exact reason and it also seems like a confusing thing to do, so I removed the code now (a little special casing is still in place, though). So fixed with commit debacb8f3afe1e004382890faa664dd15720d4ed

**Closed by mlschroe** 2016-12-08 13:54 UTC

**Comment by jlebon** [comment] 2016-12-09 20:55
Should I open a new issue for this?

**Comment by mlschroe** [comment] 2016-12-12 10:22
No, that's not a bug. It has to install "bar", and after that the "provides foo" is satisfied. The solver does not install packages if it doesn't need to.
