### ISSUE TITLE
Support indexed reads for simple queries

### ISSUE THREAD

**Issue by DemiMarie** [openSUSE/libsolv#503] opened 2022-07-01 14:35 UTC
When querying the requirements of a single package, libsolv should be able to use the equivalent of an index search directly against the on-disk database, without having to load the entire database into memory.

For such operations, queries should be O(log n) where n is the number of packages in the repository.

**Comment by mlschroe** [comment] 2022-07-04 08:47
Libsolv's business is dependency solving, which always needs the complete repositoty data. Thus it does not even keep index data that could be queried.
Having said that, loading a solv file is really fast, so this should not matter at all. What's your use case? Querying installed packages should be done by using librpm.

**Comment by DemiMarie** [comment] 2022-07-04 14:48
`dnf info "some-not-installed-package"` is currently noticibly slow, even if the metadata is all available locally.  I would have expected it to be as fast as `rpm -q "some-installed-package"`.

**Comment by mlschroe** [comment] 2022-07-05 09:07
I don't think it's the solv file loading that makes it slow. Do you have some timing numbers that show where the time is spent?

**Comment by DemiMarie** [comment] 2022-07-05 17:29
What is the best way to get these numbers?

**Comment by mlschroe** [comment] 2022-07-06 09:26
I don't know, you'll need to ask the dnf folks. libsolv is able to log the time spent in solv file loading, so I'm pretty sure that information is available in some dnf log file.

**Comment by mlschroe** [comment] 2022-07-06 13:17
Don't speculate, find out where the time is spent first.

**Comment by Conan-Kudo** [comment] 2022-09-16 13:02
@j-mracek, @jrohel: How would we measure this?

**Comment by j-mracek** [comment] 2022-09-19 09:22
It is always nice to see a statement that something is incredible slow. I used the reproducer and time returned `0.97user 0.11system 0:01.09elapsed 99%CPU`. Well from my point of view it is ok (the most of the time is used to load data from cache, calculating of checksum of repomd to ensure that the cache is valid and so on, the time required to resolve a query is in ns). If it is not ok, then provide additional information.
But you can also get completely different results - `25.95user 1.43system 0:47.73elapsed 57%CPU`
The difference is in presence of cached metadata for the first example. Then I deleted the cache and run the command again. Downloading and generating cache is simple demanding.
We can also compare results between rpm and `dnf info --installed <argument>`. Then you can see that rpm is winner, because it use direct access to sqlite DB. why dnf does not use that - because it would require to generate a different type of data structure but what will be a benefit? And what it will cast - more disk space, more resources to generate cache.
If I query 1 argument there is no real difference if it takes 0.3s or 0.0s. But If I query 1000 arguments there will be a difference, but this user case is covered in DNF5 - we use a cache of sorted solvables.
Why DNF cannot be fast as rpm? We do different things on top of different set of data.
Can we improve it? Yes, but right now it has a low priority because there are more important thing to do.

**Comment by DemiMarie** [comment] 2022-09-19 12:23
> because it use direct access to sqlite DB. why dnf does not use that - because it would require to generate a different type of data structure but what will be a benefit? And what it will cast - more disk space, more resources to generate cache.

Benefit is performance and much reduced memory use, as not all of the data needs to be loaded into memory.

**Comment by dralley** [comment] 2022-09-27 14:02
Both measurements taken with freshly updated + downloaded metadata

## With `--installed`

![flamegraph](https://user-images.githubusercontent.com/2751996/192547807-d8e7ee6a-24b0-462e-bd2d-1b25cc76df5a.svg)

```
	Command being timed: "dnf info --installed openssl"
	User time (seconds): 0.57
	System time (seconds): 0.11
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.69
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 103848
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 28902
	Voluntary context switches: 1
	Involuntary context switches: 9
....
```

## Without `--installed`

```
	Command being timed: "dnf info openssl"
	User time (seconds): 1.65
	System time (seconds): 0.17
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.84
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 176064
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 55232
	Voluntary context switches: 1
	Involuntary context switches: 42
....
```

![flamegraph](https://user-images.githubusercontent.com/2751996/192547679-eaaefc2e-609f-4683-81d9-1300f4aae174.svg)

**Comment by mlschroe** [comment] 2023-09-11 11:57
AFAIK dnf no longer caches the rpm database data since commit ee81887228c37842d3c1eb605a055f0898d07630 ("There is no benefit and only problems remains").

So there's nothing on the libsolv side to do. dnf could do rpmdb index requests and construct a temporary libsolv pool (dnf sack) if there is need to implement something faster. I'm closing this here.

**Closed by mlschroe** 2023-09-11 11:57 UTC

**Comment by DemiMarie** [comment] 2023-09-11 15:14
> AFAIK dnf no longer caches the rpm database data since commit ee81887228c37842d3c1eb605a055f0898d07630 ("There is no benefit and only problems remains").
> 
> So there's nothing on the libsolv side to do. dnf could do rpmdb index requests and construct a temporary libsolv pool (dnf sack) if there is need to implement something faster. I'm closing this here.

What would be needed to make `dnf info SOMEPACKAGE` as fast as `rpm -qi SOMEPACKAGE`?

The obvious step is to eagerly convert the downloaded XML metadata to an SQLite database and then run queries against that database.  Which repo does this belong in?

**Comment by dralley** [comment] 2023-09-11 15:23
> The obvious step is to eagerly convert the downloaded XML metadata to an SQLite database and then run queries against that database. Which repo does this belong in?

Something similar will be needed for https://github.com/fedora-infra/mdapi when Fedora eventually stops producing the sqlite metadata.

sqliterepo_c essentially does this already but the ergonmics of how that works isn't ideal IIRC. I don't remember details but when I tried to use it from mdapi it was a bit painful.
